services:
  app:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "npm install
      && npm run build:server
      && (node dist-server/index.js &)
      && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 8081
      SESSION_COOKIE_SECRET: dev-session-secret-change-me
      REDIS_URL: redis://redis:6379
      CHOKIDAR_USEPOLLING: "true"

      MATRIX_AUTH_SECRET: replace-with-strong-secret
      MATRIX_OIDC_CLIENT_ID: 01KEKV3RZ8D3823SS78THKT753
      MATRIX_OIDC_SCOPE: openid email
      MATRIX_OIDC_CLIENT_SECRET: 0105CoUyvqwtrORxELqsgieZ1yHxNiKgHIfy812SZ0124P3k3l8s76FZHlLXQtCJr
      MATRIX_OIDC_ISSUER: https://matrix.datenba.ch/auth/.well-known/openid-configuration
      MATRIX_OIDC_REDIRECT_URI: http://localhost:8080/api/auth/callback
      MATRIX_HOMESERVER_URL: https://matrix.datenba.ch
      MATRIX_ACCESS_TOKEN: mpt_0KSCGHx4KE7zUWjKCvemNTcks93PNt_KlyjT1
      MATRIX_ADMIN_API_BASE: https://matrix.datenba.ch/auth
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  app-node-modules:
  redis-data:
